#!/usr/bin/env python3
"""Flappy80 bird art: 40 x 12 VDC pixels (5 x 2 cells), three wing positions.

Drawn by hand in display proportions: one VDC pixel row is about 2.4 pixels
wide on a 4:3 monitor. Each 8-pixel column has one colour (COLOURS), so the
original's dark outline becomes gaps showing the sky.

    python3 tools/bird_art.py            writes src/bird_art.h
    python3 tools/bird_art.py preview.png  renders the wing frames
"""
import struct
import sys
import zlib
from pathlib import Path

W, H = 40, 12
WINGS = ('up', 'mid', 'down')
# RGBI colour per 8-pixel column: body, body, body, face/eye, lips.
COLOURS = (13, 13, 13, 15, 9)

BODY = [(11, 23), (7, 23), (4, 23), (2, 23), (1, 23), (0, 23),
        (0, 23), (0, 31), (1, 30), (2, 29), (4, 27), (8, 23)]
EYE = {0: (24, 29), 1: (24, 30), 2: (24, 31), 3: (24, 31), 4: (24, 31), 5: (24, 30)}
PUPIL = [(x, y) for x in (28, 29, 30) for y in (2, 3)]
LIPS = {6: (32, 38), 7: (32, 39), 9: (32, 37), 10: (32, 35)}
# Wing ovals (rows -> x span), cut out of the body in sky colour.
WING_SHAPES = {
    'up':   {2: (6, 12), 3: (4, 14), 4: (4, 14), 5: (6, 12)},
    'mid':  {4: (5, 13), 5: (3, 15), 6: (3, 15), 7: (5, 13)},
    'down': {6: (5, 13), 7: (3, 15), 8: (3, 15), 9: (4, 14), 10: (6, 12), 11: (8, 10)},
}


def bird(wing):
    """Rows of 40 booleans for one wing position."""
    g = [[False] * W for _ in range(H)]

    def span(y, a, b, v=True):
        for x in range(a, b + 1):
            g[y][x] = v
    for y, (a, b) in enumerate(BODY):
        span(y, a, b)
    for y, (a, b) in EYE.items():
        span(y, a, b)
    span(6, 24, 31, False)  # separates the eye from the white face below
    for x, y in PUPIL:
        g[y][x] = False
    for y, (a, b) in LIPS.items():
        span(y, a, b)
    shape = WING_SHAPES[wing]
    for y, (a, b) in shape.items():
        span(y, a, b, False)
    return g


def rows_as_bytes(wing):
    """Each row as five bytes, most significant bit leftmost."""
    out = []
    for row in bird(wing):
        out.append([sum(0x80 >> i for i in range(8) if row[c * 8 + i]) for c in range(5)])
    return out


def header():
    lines = ['/* Generated by tools/bird_art.py; edit the art there. */',
             '#define BIRD_WINGS %d' % len(WINGS),
             'static const char bird_colours[5] = {%s};' % ', '.join(map(str, COLOURS)),
             'static const char bird_art[BIRD_WINGS][%d][5] = {' % H]
    for wing in WINGS:
        lines.append('  { /* %s */' % wing)
        for row in rows_as_bytes(wing):
            lines.append('    {%s},' % ', '.join('0x%02x' % b for b in row))
        lines.append('  },')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def preview(path, sx=4, sy=10, pad=6):
    pal = {6: (0, 170, 170), 13: (255, 255, 85), 15: (255, 255, 255), 9: (255, 85, 85)}
    cw, ch = (W + pad) * len(WINGS) + pad, H + 2 * pad
    img = [[pal[6]] * (cw * sx) for _ in range(ch * sy)]
    for n, wing in enumerate(WINGS):
        ox = pad + n * (W + pad)
        for y, row in enumerate(bird(wing)):
            for x, on in enumerate(row):
                if on:
                    for yy in range((pad + y) * sy, (pad + y + 1) * sy):
                        for xx in range((ox + x) * sx, (ox + x + 1) * sx):
                            img[yy][xx] = pal[COLOURS[x // 8]]
    h, w = len(img), len(img[0])
    raw = b''.join(b'\0' + bytes(v for p in row for v in p) for row in img)

    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d))
    Path(path).write_bytes(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
                           + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'IEND', b''))


if __name__ == '__main__':
    if len(sys.argv) > 1:
        preview(sys.argv[1])
    else:
        Path(__file__).resolve().parent.parent.joinpath('src/bird_art.h').write_text(header())
